language: cpp

sudo: false
dist: trusty

#cache:
#  directories:
#    - $HOME/travis-cache

os:
  - linux

addons:
  apt:
    sources:
      # sources list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
      #- boost-latest
      - sourceline: 'ppa:qbittorrent-team/qbittorrent-stable'
      - sourceline: 'ppa:beineri/opt-qt551-trusty'
      - sourceline: 'ppa:adrozdoff/cmake'
    packages:
      - libssl-dev
      - libtorrent-rasterbar-dev
      - [cmake, ninja-build]
      - [qt55base, qt55svg, qt55tools]
      - [libboost-dev, libboost-system-dev]

compiler:
  - clang

before_install:
    # Qt 5
    PATH=/opt/qt55/bin:${PATH}

script:
  - mkdir build
  - cd build
  - cmake -G "Ninja" ..
  - ninja -v
